name: daxtacey
favicon: null
layout_spectrum: 0.4382361499592662
typography_spectrum: 0.5032421096693724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4451551779638976
  lightness: 0.09654813236556947
  saturation: 0.7811974924989045
  rhythmicContrast: 0.8635867254342884
purpose: []
